### ISSUE TITLE
Criar lista de produtos (static) - Falar com grupo Loja

### ISSUE THREAD

**Issue by fabiotadashi** [fabiotadashi/Fornecedor#3]

**Comment by dsaouda** [comment]
Fábio, podemos trabalhar com essa lista?

https://github.com/dsaouda/fiap-webservice-loja/blob/develop/loja-api/src/main/java/com/github/dsaouda/fiap/webservice/loja/api/repository/ProdutoRepository.java#L18-L31

Existem 14 produtos pegados do submarino, só para não ficarmos no prod1, prod2, teste, etc...

Tudo bem para vocês?

O nosso objeto é um pouco diferente, nós precisamos manter estoque, então ignorem a propriedade quantidadeEstoque, por que acho que vocês não precisam.

**Comment by michelbarbosa** [comment]
@dsaouda , feito. Quando o Fabio publicar, aviso.

**Comment by fabiotadashi** [comment]
@dsaouda @michelbarbosa publicado! Acho que deu eu um problema de encoding na acentuação (pelo menos no SoapUI aqui)
